---
title: "고급통계분석 - Assignment01"
author: "20220866 문가영"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Problem 1.

```{r}
set.seed(1)
n = 200
x = seq(0, 1, length.out = n)
y = sin(2*pi*x) + rnorm(n, sd = 0.15)
```


#### (a). 

```{r}
df = data.frame(x, y)
write.csv(df, file = 'data/problem1.csv', row.names = FALSE)
```


#### (d).

**GitHub 저장소 링크:** [20220866 문가영 GitHub 링크](https://github.com/Ga-young-Moon/Advanced-Statistical-Analysis)
\

### Problem 2.

#### (a).

버블 정렬 함수 구현:
```{r}
# 버블 정렬
bubble_sort <- function(vec, decreasing = FALSE){
  n = length(vec) # 길이가 n인 입력 벡터
  
  # 오름차순 옵션
  if (decreasing == FALSE){
    for (i in 1:(n-1)){
      for (j in 1:(n-i)){
        if (vec[j] > vec[j+1]){
          temp = vec[j]
          vec[j] = vec[j+1]
          vec[j+1] = temp
        }
      }
    }
  }
  
  # 내림차순 옵션
  else{
    for (i in 1:(n-1)){
      for (j in 1:(n-i)){
        if (vec[j] < vec[j+1]){
          temp = vec[j]
          vec[j] = vec[j+1]
          vec[j+1] = temp
        }
      }
    }
  }
  return(vec)
}
```


구현한 버블 정렬 알고리즘 실행 결과 확인:
```{r}
set.seed(1)
x = runif(10)

print('***원본 벡터 (x)***')
print(x)

# 1. 오름차순 정렬 (decreasing = FALSE)
x_asc = bubble_sort(x, decreasing = FALSE)
print('***1. 오름차순 결과***')
print(x_asc)

# 2. 내림차순 정렬(decreasing = TRUE)
x_desc = bubble_sort(x, decreasing = TRUE)
print('***2. 내림차순 결과***')
print(x_desc)
```


#### (b).

퀵 정렬 함수 구현:
```{r}
# 퀵 정렬
quick_sort <- function(vec, decreasing = FALSE){
  n = length(vec) # 길이가 n인 입력 벡터
  
  # 재귀 종료 조건
  if (n <= 1){
    return(vec)
  }
  
  # Pivot 분리
  pivot <- vec[1]
  rest <- vec[-1]
  
  # 분할
  # 오름차순 옵션
  if (decreasing == FALSE){
    Left <- rest[rest <= pivot]
    Right <- rest[rest > pivot]
  }
  
  # 내림차순 옵션
  else{
    Left <- rest[rest >= pivot]
    Right <- rest[rest < pivot]
  }
  
  # 재귀 호출
  Left_sort <- quick_sort(Left, decreasing)
  Right_sort <- quick_sort(Right, decreasing)
  
  # 결합
  return(c(Left_sort, pivot, Right_sort))
}
```


구현한 퀵 정렬 알고리즘 실행 결과 확인:
```{r}
set.seed(1)
x = runif(10)

print('***원본 벡터 (x)***')
print(x)

# 1. 오름차순 정렬 (decreasing = FALSE)
x_asc = quick_sort(x, decreasing = FALSE)
print('***1. 오름차순 결과***')
print(x_asc)

# 2. 내림차순 정렬(decreasing = TRUE)
x_desc = quick_sort(x, decreasing = TRUE)
print('***2. 내림차순 결과***')
print(x_desc)
```
\

### Problem 3.

#### (a).

수치 미분 함수 구현:
```{r}
# 수치 미분
num_diff <- function(f, x, h= 1e-6, method){
  if (method == 'forward'){
    result <- (f(x+h) - f(x)) / h
    return(result)
  }
  else if (method == 'backward'){
    result <- (f(x) - f(x-h)) / h
    return(result)
  }
  else if (method == 'central'){
    result <- (f(x+h) - f(x-h)) / (2*h)
    return(result)
  }
  else{
    stop('Choose the method you want to use.')
  }
}
```


구현한 수치 미분 알고리즘 실행 결과 확인:
```{r}
n <- 100
x <- seq(0, 2*pi, length.out = n)

# f 함수와 실제 도함수(f`) 정의
f <- function(x){
  return(cos(x) - x)
}

f_prime <- function(x){
  return(-sin(x) - 1)
}

# 구현한 함수 적용
# 1. 전진차분
y_for <- num_diff(f, x, method= 'forward')

# 2. 후진차분
y_back <- num_diff(f, x, method= 'backward')

# 3. 중심차분
y_cen <- num_diff(f, x, method= 'central')
```


시각화:
```{r}
library(ggplot2)

# 해석적 도함수 정의
y_prime <- f_prime(x)

# 시각화
# 1. 전진차분
df_for <- data.frame(x = x, analytic = y_prime, forward = y_for)

p1 <- ggplot(df_for, aes(x = x)) +
  geom_line(aes(y = analytic), color= 'black', size= 1.15) +
  geom_line(aes(y = forward), color= 'red', size = 0.9) +
  labs(title= '1. 전진차분 vs 해석적 도함수',
       x= 'x',
       y= 'f`(x)')

# 2. 후진차분
df_back <- data.frame(x= x, analytic = y_prime, backward = y_back)

p2 <- ggplot(df_back, aes(x = x)) +
  geom_line(aes(y = analytic), color= 'black', size= 1.15) +
  geom_line(aes(y = backward), color= 'green', size = 0.9) +
  labs(title= '2. 후진차분 vs 해석적 도함수',
       x= 'x',
       y= 'f`(x)')

# 3. 중심차분
df_cen <- data.frame(x= x, analytic = y_prime, central = y_cen)

p3 <- ggplot(df_cen, aes(x = x)) +
  geom_line(aes(y = analytic), color= 'black', size= 1.15) +
  geom_line(aes(y = central), color= 'blue', size = 0.9) +
  labs(title= '3. 중심차분 vs 해석적 도함수',
       x= 'x',
       y= 'f`(x)')


# plot 출력
print(p1)
print(p2)
print(p3)
```


#### (b).

```{r}

```

